SELECT CONVERT(nchar(4),YEAR(rD.DTZAPIS)) +'/' + '0' + CONVERT(nchar(1),DATEPART(qq,rD.DTZAPIS)) as Period,
 ROUND(sum(rd.SUMA_ZIELONEJ)/1000,1) as [TotalIn],
ROUND(sum(rd.ILOSC_PALONA)/1000,1) As [TotalOut],
ROUND(100*(1-(sum(rd.ILOSC_PALONA)/sum(rd.SUMA_ZIELONEJ))),2) as TotalLoss,
ROUND(sum(CASE WHEN rD.NUMERPIECA=3000 THEN rD.SUMA_ZIELONEJ ELSE NULL END)/1000,1) as [r3In], 
ROUND(sum(CASE WHEN rD.NUMERPIECA=3000 THEN rD.ILOSC_PALONA ELSE NULL END)/1000,1) as [r3Out],
ROUND((1-(sum(CASE WHEN rD.NUMERPIECA=3000 THEN rD.ILOSC_PALONA ELSE NULL END)/1000)/(sum(CASE WHEN rD.NUMERPIECA=3000 THEN rD.SUMA_ZIELONEJ ELSE NULL END)/1000))*100,2) as r3Loss,
ROUND(sum(CASE WHEN rD.NUMERPIECA=4000 THEN rD.SUMA_ZIELONEJ ELSE NULL END)/1000,1) as [r4In], 
ROUND(sum(CASE WHEN rD.NUMERPIECA=4000 THEN rD.ILOSC_PALONA ELSE NULL END)/1000,1) as [r4Out],
ROUND((1-(sum(CASE WHEN rD.NUMERPIECA=4000 THEN rD.ILOSC_PALONA ELSE NULL END)/1000)/(sum(CASE WHEN rD.NUMERPIECA=4000 THEN rD.SUMA_ZIELONEJ ELSE NULL END)/1000))*100,2) as r4Loss
FROM (select DISTINCT z.NUMERPIECA, z.SUMA_ZIELONEJ, z.ILOSC_PALONA, z.DTZAPIS, zl.OrderNumber, zl.MaterialNumber, zl.NAZWARECEPT from ZLECENIA_PALONA z Join ZLECENIAWARTOSCI w ON z.IDZLECENIE = w.IDZLECENIE JOIN ZLECENIA zl on w.IDZLECENIE = zl.IDZLECENIE) as rD 
WHERE rd.MaterialNumber=34005471 AND Year(rd.DTZAPIS) =2017
GROUP BY CONVERT(nchar(4),YEAR(rD.DTZAPIS)) +'/' + '0' + CONVERT(nchar(1),DATEPART(qq,rD.DTZAPIS))
ORDER BY Period;

