Use [Prima]
select DISTINCT
zlec.MaterialNumber,
	(SELECT AVG(sub.green) FROM
	(SELECT TOP(10) z.SUMA_ZIELONEJ as green FROM ZLECENIA_PALONA z Join ZLECENIAWARTOSCI w ON z.IDZLECENIE = w.IDZLECENIE 
							JOIN ZLECENIA zl on w.IDZLECENIE = zl.IDZLECENIE 
							WHERE z.NUMERPIECA=3000 AND z.SUMA_ZIELONEJ>100 AND zlec.MaterialNumber=zl.MaterialNumber ORDER BY z.DTZAPIS DESC) sub) As RN3000,
	(SELECT AVG(sub.green) FROM
	(SELECT TOP(10) z.SUMA_ZIELONEJ as green FROM ZLECENIA_PALONA z Join ZLECENIAWARTOSCI w ON z.IDZLECENIE = w.IDZLECENIE 
							JOIN ZLECENIA zl on w.IDZLECENIE = zl.IDZLECENIE 
							WHERE z.NUMERPIECA=4000 AND z.SUMA_ZIELONEJ>100 AND zlec.MaterialNumber=zl.MaterialNumber ORDER BY z.DTZAPIS DESC) sub) As RN4000  
FROM ZLECENIA zlec
order BY zlec.materialNumber;

