SELECT
  LU.LOADUNIT_NR,
  SPC.IS_BULK,
  LU.LOADUNIT_ID,
  SP.SP_NR,
  SP.SP_ID,
  SPC.NAME AS SPC_NAME,
  LUC.POSITION_NR,
  P.PRODUCT_NR,
  P.name,
  P.PRODUCT_ID,
  LUC.PROD_SERIAL_ID,
  PS.SERIAL_NR,
  LUC.DATE_EXPIRE,
  LUC.BU_QUANTITY,
  PKGL_FL.BU_QUANTITY AS MAX_BU_QUANTITY,
  PKGL_BU.INFO AS OPAKOWANIE,
  PKGH.HAS_FULL_LU,
  V_SUM_Q.BU_QUANTITY_LU,
  SA.wh_id,
  LU.status_quality,
  LU.c_Date
FROM
  LOAD_UNITS_FAST LU JOIN QWHV_FULFILL_AUX V_SUM_Q ON V_SUM_Q.loadunit_id = LU.LOADUNIT_ID
  JOIN LU_CONTENTS_FAST LUC ON LU.LOADUNIT_ID = LUC.LOADUNIT_ID 
  JOIN QCM_PRODUCTS P ON LUC.PRODUCT_ID = P.PRODUCT_ID 
  JOIN QCM_PROD_SERIALS PS ON LUC.PRODUCT_ID = PS.PRODUCT_ID AND LUC.PROD_SERIAL_ID = PS.PROD_SERIAL_ID
  JOIN STORAGEPLACES SP ON LU.SP_ID = SP.SP_ID 
  JOIN SP_CLASSES SPC ON SP.SP_CLASS_ID = SPC.SP_CLASS_ID 
  JOIN QCM_PACKAGE_HEADERS PKGH ON P.PRODUCT_ID = PKGH.PRODUCT_ID 
  JOIN QCM_PACKAGE_LEVELS PKGL_BU ON PKGH.PACKAGE_ID = PKGL_BU.PACKAGE_ID
  JOIN STORAGEAREAS SA ON SA.SA_ID = SP.SA_ID 
  JOIN SA_CLASSES SAC ON SA.SA_CLASS_ID = SAC.SA_CLASS_ID 
  LEFT OUTER JOIN QCM_PACKAGE_LEVELS PKGL_FL ON PKGL_FL.PACKAGE_ID = PKGH.PACKAGE_ID 
WHERE
   PKGL_BU.LEVEL_NR = 0  AND 
   SAC.IS_STORAGE = 'T' AND
   PKGL_BU.status = 'OK' AND 
   PKGL_FL.is_full_lu = 'T' AND 
   PKGL_FL.status = 'OK'